HICC-REBOOT/HICC-REBOOT-Frontend

frontend/README.md, frontend/src/config.ts, frontend/src/utils/axios.ts, frontend/tsconfig.paths.json
=> chore: 개발환경 설명 추가

frontend/README.md
=> docs: 개발문서 수정

frontend/package-lock.json, frontend/package.json, frontend/src/constants/token.ts, frontend/src/index.tsx, frontend/src/utils/axios.ts, frontend/src/utils/cookie.ts, frontend/src/utils/request.ts
=> chore: react-cookie를 사용하여 리프레시 토큰 관리

frontend/package-lock.json, frontend/package.json, frontend/src/query/get/useServerSidePagination.tsx, frontend/src/utils/axios.ts
=> refactor: pagination 정리

README.md
=> docs: 팀원 소개 추가;

frontend/src/App.tsx, frontend/src/query/get/useServerSidePagination.tsx, frontend/src/utils/axios.ts, frontend/tsconfig.paths.json
=> refactor: 절대 경로 수정

frontend/src/pages/Login/Login.style.tsx
- 데스크탑 화면일 때 앱바에 로그인 페이지 일부가 가려지던 오류 수정
-
-
=> [Fix]: 로그인 페이지 Bug Fix

frontend/src/components/signup/EnterInfo.tsx, frontend/src/components/signup/style/EnterInfo.style.tsx
=> [refactor]: enterInfo 반응형 적용

frontend/src/pages/SignUp/SignUP.tsx
=> refactor: signup 반응형 적용

frontend/src/components/admin/ChangeGrade.tsx, frontend/src/components/admin/MemberInfo.tsx
=> [design]: 드롭다운 width 조정

frontend/package.json
=> chore: package.json 수정

frontend/package.json
=> chore: https -> http 임시로 변환

frontend/package.json, frontend/src/components/admin/ChangeGradeCollapse.tsx, frontend/src/components/admin/MemberItem.tsx, frontend/src/components/common/popup/confirm/ExtensionModal.style.tsx, frontend/src/components/common/tab/Tab.tsx, frontend/src/components/community/common/WriteInfo.tsx, frontend/src/components/home/RecentNews.tsx, frontend/src/components/signup/EnterInfo.tsx, frontend/src/constants/keys.ts, frontend/src/hooks/useAuth.ts, frontend/src/libs/store/presidentStore.ts, frontend/src/pages/Admin/Admin.tsx, frontend/src/query/get/useServerSidePagination.tsx, frontend/src/utils/Authorization.ts, frontend/src/utils/isMoreThanExecutive.ts
[FEAT]: 회원가입 이메일 추가, 회장위임 추가, 회원리스트 선택한 아이템 컬러 추가
-회원가입 이메일 추가, 
-회장위임 추가, 
-회원리스트 선택한 아이템 컬러 추가
-
-
-
=> [FEAT]: 회원가입 이메일 추가, 회장위임 추가, 회원리스트 선택한 아이템 컬러 추가

frontend/src/components/admin/style/MemberInfo.style.tsx, frontend/src/components/signup/EnterInfo.tsx
회원가입 전번오류수정 및 관리페이지 리스트 번쩍임 해결
-회원가입 전번오류수정
-관리페이지 리스트 번쩍임 해결
-
-
-
=> [FIX]: 회원가입 전번오류수정 및 관리페이지 리스트 번쩍임 해결

frontend/src/components/community/CommunityType.ts, frontend/src/components/community/detail/comment/Comment.tsx
- 복잡하던 대댓글 로직을 쉽게 변경했습니다. (백엔드가 쉽게 전달해줘서)
-
-
- 보이는 상의 변경이 아니라 사진은 없어용
=> [refactor] 대댓글 백엔드 변경으로 인한 리팩터링

frontend/src/components/common/footer/Footer.tsx, frontend/src/components/community/detail/comment/EachComment.tsx, frontend/src/components/community/detail/comment/WriteComment.tsx, frontend/src/components/community/list/filter/Filter.tsx, frontend/src/hooks/useChangeComment.ts, frontend/src/pages/auth/Login/Login.style.tsx, frontend/src/pages/auth/Login/Login.tsx, frontend/src/query/get/useGetFooterInfo.ts, frontend/src/utils/axios.ts, frontend/src/utils/keyboard.ts
- 회장 정보를 api를 통해 불러오도록 변경했습니다.
- 엔터 키를 누르면 댓글이 작성되고, 목록 검색이 됩니다.
- 로그인 시에 엔터를 누르면 로그인이 시도됩니다.
- 500에러 시 경고창 활성화했습니다.
-
-
=> [Fix] 회장 정보를 api를 통해 불러오도록 변경, 엔터 키 입력 제출 활성화

frontend/src/utils/axios.ts
=> fix: 회원가입할 때 중복된 아이디면 에러 발생

frontend/src/components/admin/style/MemberInfo.style.tsx, frontend/src/query/post/usePostSignup.ts
아이디(학번) 중복시 경고창 추가
-아이디(학번) 중복시 경고창 추가
-
-
-
=> [Fix]: 아이디(학번) 중복시 경고창 추가

frontend/src/components/mypage/MyComments.tsx, frontend/src/components/mypage/MyWritings.tsx, frontend/src/components/mypage/mypage/CommentsInner.tsx, frontend/src/components/mypage/mypage/WritingsInner.tsx
=> [Feature]: mypage 스켈레톤 추가

frontend/src/components/mypage/style/MyInfo.style.tsx
- 회원 라벨 폰트 수정 및 이름 가운데 정렬
- 없음
- 없음
=> [design]: 회원 라벨 폰트 수정 및 이름 가운데 정렬

frontend/src/components/admin/ApprovalMemberItem.tsx, frontend/src/components/admin/ChangeGradeCollapse.tsx
페이지 전환시 collapse 유지현상 해결 및 모달 extensionModal로 변경
-페이지 전환시 collapse 유지현상 해결
-모달 extensionModal로 변경
-
-
-
=> fix: 페이지 전환시 collapse 유지현상 해결 및 모달 extensionModal로 변경

frontend/src/components/common/popup/confirm/Confirm.tsx, frontend/src/query/delete/useDeleteApproval.ts, frontend/src/query/delete/useDeleteArticle.ts, frontend/src/query/delete/useDeleteMember.ts, frontend/src/query/get/useServerSidePagination.tsx, frontend/src/query/patch/usePatchApproval.ts, frontend/src/query/patch/usePatchChangeGrade.ts, frontend/src/query/post/usePostLogout.ts
- 관리자에서는 데이터 변경 시 새로고침 되도록 변경
- 상태가 변하면 무한스크롤 때 반영되지 않는 버그때문입니다.
- 관리자만 볼 수 있는 페이지라 ux가 조금 떨어져도 괜찮다는 판단입니다.
-
-
=> fix: 관리자에서는 데이터 변경 시 새로고침 되도록 변경

frontend/src/components/home/Activity.tsx, frontend/src/components/home/style/Activity.style.tsx
- 메인 홈 화면 엑티비티 글자 줄 바꿈 및 위치 수정
- joinus 일부가 블러 처리되다 안 되는 현상은 어떻게 처리해야할지 모르겠음
- 없음
=> [design]: 메인 홈 화면 엑티비티 글자 줄 바꿈 및 위치 수정

frontend/src/components/common/popup/confirm/ExtensionModal.style.tsx, frontend/src/components/signup/EnterInfo.tsx
FIX: modal 사이즈 flex하게 변경 및 PhoneNumError 정규식 수정
- modal 사이즈 flex하게 변경 
- PhoneNumError 정규식 수정
-
-
-
=> FIX: modal 사이즈 flex하게 변경 및 PhoneNumError 정규식 수정

frontend/src/components/common/header/Header.tsx
=> fix: 관리자일 때 마이페이지가 헤더에 두 번 나타나는 현상 해결

frontend/src/constants/keys.ts, frontend/src/pages/community/Community.style.tsx, frontend/src/query/post/usePostLogin.ts, frontend/src/query/post/usePostLogout.ts, frontend/src/utils/axios.ts
- 인증 에러 시 로그인 후 처음 접속한 페이지로 이동하는 기능 추가했습니다.
-
-
-
=> feat: 인증 에러 시 로그인 후 처음 접속한 페이지로 이동하는 기능 추가

frontend/src/components/common/footer/Footer.tsx, frontend/src/components/layout/Layout.tsx, frontend/src/query/get/useGetFooterInfo.ts
=> fix: 회장 정보 오류여도 에러 발생하지 않도록 설정

frontend/src/components/common/header/Header.tsx, frontend/src/components/common/header/MobileHeader.tsx, frontend/src/components/common/header/style/Header.style.tsx, frontend/src/components/common/header/style/MobileHeader.style.tsx, frontend/vite.config.ts
=> 로고 이미지 보이지 않는 문제 해결
